// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHzFVs1ULZC-2k-VVHbh2E8zR0qhx_RpY',
    appId: '1:89035561301:web:4c7c99c2f3351f8ba6b7dc',
    messagingSenderId: '89035561301',
    projectId: 'miniproject2-c2830',
    authDomain: 'miniproject2-c2830.firebaseapp.com',
    storageBucket: 'miniproject2-c2830.firebasestorage.app',
    measurementId: 'G-F7JZ8N1ZGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWvqYVxiE3jfrqamGTnluIHNpjMeMkvF8',
    appId: '1:89035561301:android:b74310673af2e652a6b7dc',
    messagingSenderId: '89035561301',
    projectId: 'miniproject2-c2830',
    storageBucket: 'miniproject2-c2830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_aBTFUPjGvKubw4ANIqje-IJId7s1brY',
    appId: '1:89035561301:ios:c1640daba10ea4a0a6b7dc',
    messagingSenderId: '89035561301',
    projectId: 'miniproject2-c2830',
    storageBucket: 'miniproject2-c2830.firebasestorage.app',
    iosBundleId: 'com.example.tournamentTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_aBTFUPjGvKubw4ANIqje-IJId7s1brY',
    appId: '1:89035561301:ios:c1640daba10ea4a0a6b7dc',
    messagingSenderId: '89035561301',
    projectId: 'miniproject2-c2830',
    storageBucket: 'miniproject2-c2830.firebasestorage.app',
    iosBundleId: 'com.example.tournamentTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHzFVs1ULZC-2k-VVHbh2E8zR0qhx_RpY',
    appId: '1:89035561301:web:fcd7bdde71a105c5a6b7dc',
    messagingSenderId: '89035561301',
    projectId: 'miniproject2-c2830',
    authDomain: 'miniproject2-c2830.firebaseapp.com',
    storageBucket: 'miniproject2-c2830.firebasestorage.app',
    measurementId: 'G-XQZMFXVPM0',
  );
}
